# Generated by Django 5.2.1 on 2025-05-29 06:06

import oauth2login.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavanaDiscordUsers',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('public_flags', models.IntegerField()),
                ('flags', models.IntegerField(null=True)),
                ('locale', models.CharField()),
                ('discord_tag', models.TextField(null=True)),
                ('avatar', models.CharField(null=True)),
                ('mfa_enabled', models.CharField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('has_module_perms', models.BooleanField(default=True)),
                ('has_module_permission', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(null=True)),
            ],
            managers=[
                ('objects', oauth2login.managers.SavanaUserOauth2Manager()),
            ],
        ),
    ]
