name: Savana Django Service

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up python latest
        uses: actions/setup-python@v4
        with:
            python-version: '3.12'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage 
          pip install  pytest-django

      #- name: Lint with flake8
        #run:
          Epip install flake8
          flake8
      #- name: Run tests with term report
        #run: pytest --cov=sales --cov-report=term-missing

      #- name: Savana application run tests
        #run:
          #pytest







